//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.Dominio.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titulos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titulos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nucleo.Dominio.Recursos.Titulos", typeof(Titulos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros de Auditoria.
        /// </summary>
        public static string Auditoria_PageTitle {
            get {
                return ResourceManager.GetString("Auditoria_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción:.
        /// </summary>
        public static string AuditoriaCriteria_Accion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Accion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha hasta:.
        /// </summary>
        public static string AuditoriaCriteria_FechaFinal_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_FechaFinal_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha desde:.
        /// </summary>
        public static string AuditoriaCriteria_FechaInicio_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_FechaInicio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad:.
        /// </summary>
        public static string AuditoriaCriteria_Funcionalidad_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Funcionalidad_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación:.
        /// </summary>
        public static string AuditoriaCriteria_Identificador_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Identificador_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        public static string AuditoriaCriteria_Usuario_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Usuario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string AuditoriaItem_Accion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Accion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string AuditoriaItem_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad.
        /// </summary>
        public static string AuditoriaItem_Funcionalidad_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Funcionalidad_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string AuditoriaItem_Identificacion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Identificacion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string AuditoriaItem_Registro_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Registro_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string AuditoriaItem_Usuario_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Usuario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sus Diarios Temáticos Pendientes de Registro.
        /// </summary>
        public static string DiariosTematicosPendientes {
            get {
                return ResourceManager.GetString("DiariosTematicosPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Diario Temático.
        /// </summary>
        public static string DiarioTematicoEditar {
            get {
                return ResourceManager.GetString("DiarioTematicoEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Diario Temático.
        /// </summary>
        public static string DiarioTematicoRegistrar {
            get {
                return ResourceManager.GetString("DiarioTematicoRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha actual.
        /// </summary>
        public static string General_CurrentDate {
            get {
                return ResourceManager.GetString("General_CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string General_Date {
            get {
                return ResourceManager.GetString("General_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string General_FullName {
            get {
                return ResourceManager.GetString("General_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string General_Identification {
            get {
                return ResourceManager.GetString("General_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulo.
        /// </summary>
        public static string General_Module {
            get {
                return ResourceManager.GetString("General_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han ingresado los campos obligatorios o existen datos no válidos.
        /// </summary>
        public static string General_ValidationSummary_Message {
            get {
                return ResourceManager.GetString("General_ValidationSummary_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agenda Docente.
        /// </summary>
        public static string HorarioDocente {
            get {
                return ResourceManager.GetString("HorarioDocente", resourceCulture);
            }
        }
    }
}
