---TSEG_SISTEMA

INSERT [dbo].[TSEG_SISTEMA] ([SIS_CODIGO], [SIS_NOMBRE], [SIS_DESCRIPCION], [VERSION]) VALUES (N'SISTEMASIS',N'Sistema SIS', N'Sistema SIS', 1);

---TSEG_USUARIO

--Clave para login en TRESDES -adminadmin- 
--ClaveEncriptar: Encuest@2018 y ClaveEncriptada: w8CCXuvizyp/bw4jzmQ99w==
INSERT [dbo].[TSEG_USUARIO] ([USR_CUENTA], [VERSION],[USR_FECHA_CREACION],[USR_FECHA_ACTUALIZACION],[USR_USUARIO_CREACION_ID],[USR_USUARIO_ACTUALIZACION_ID],[USR_ESTADO],[USR_CLAVE])VALUES (N'admin',1,GETDATE(),NULL,1,NULL,1,N'w8CCXuvizyp/bw4jzmQ99w==');

---TSEG_ROL

INSERT [dbo].[TSEG_ROL] ([ROL_CODIGO], [ROL_NOMBRE], [ROL_ESADMINISTRADOR], [VERSION],[ROL_ESEXTERNO],[ROL_FECHA_CREACION],[ROL_FECHA_ACTUALIZACION],[ROL_USUARIO_CREACION_ID],[ROL_USUARIO_ACTUALIZACION_ID],[ROL_URL],[ROL_PARAMETROS])VALUES (N'Admin',N'Super Administrador', 1, 1, 1,GETDATE(),NULL,(SELECT [USR_ID] FROM [TSEG_USUARIO] WHERE [USR_Cuenta]='admin'),NULL,NULL,NULL);

---TSEG_USUARIO_ROL

INSERT [dbo].[TSEG_USUARIO_ROL] ([ROL_ID], [USR_ID], [VERSION]) VALUES ((SELECT [ROL_ID] FROM [dbo].[TSEG_ROL] WHERE [ROL_CODIGO] = N'Admin' COLLATE DATABASE_DEFAULT),(SELECT [USR_ID] FROM [TSEG_USUARIO] WHERE [USR_Cuenta]='admin'), 1);
