USE [FarmaciaLocal]
GO
DELETE FROM [dbo].[TSEG_USUARIO_ROL]
WHERE [ROL_ID] != (SELECT [ROL_ID]
  FROM [dbo].[TSEG_ROL]
  WHERE [ROL_CODIGO]='Admin')
DELETE FROM [dbo].[TNEG_FARMACIA_USUARIO]
DELETE FROM [dbo].[TSEG_USUARIO]
      WHERE [USR_CUENTA] != 'admin'
DELETE FROM [dbo].[TNEG_DEPOSITO_BANCARIO]
DELETE FROM [dbo].[TNEG_SUSCRIPCION]
DELETE FROM [dbo].[TADM_PERSONA]
DELETE FROM [dbo].[TNEG_PRO_FAR_PRO_TEXTO]
DELETE FROM [dbo].[TNEG_PROMOCION_TEXTO]
DELETE FROM [dbo].[TNEG_PROMOCION_VISUAL_FARMACIA]
DELETE FROM [dbo].[TNEG_PROMOCION_VISUAL]
DELETE FROM [dbo].[TNEG_PRODUCTO_FARMACIA]
DELETE FROM [dbo].[TNEG_HORARIO_ATENCION]
DELETE FROM [dbo].[TNEG_HORARIO_DIFERIDO]
DELETE FROM [dbo].[TNEG_FARMACIA]
GO












