//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.Dominio.Models.Temporal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionDocente> TNEG_ASIGNACION_DOCENTE { get; set; }
        public virtual DbSet<ComponenteEducativo> TNEG_COMPONENTE_EDUCATIVO { get; set; }
        public virtual DbSet<Matricula> TNEG_MATRICULA { get; set; }
        public virtual DbSet<TNEG_RESULTADOS> TNEG_RESULTADOS { get; set; }
        public virtual DbSet<TSEG_USUARIO_ROL> TSEG_USUARIO_ROL { get; set; }
    }
}
