//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.Dominio.Models.Temporal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNEG_COMPONENTE_EDUCATIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TNEG_COMPONENTE_EDUCATIVO()
        {
            this.TNEG_ASIGNACION_DOCENTE = new HashSet<AsignacionDocente>();
            this.TNEG_MATRICULA = new HashSet<TNEG_MATRICULA>();
        }
    
        public int COE_ID { get; set; }
        public string COE_CODIGO { get; set; }
        public string COE_NOMBRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionDocente> TNEG_ASIGNACION_DOCENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNEG_MATRICULA> TNEG_MATRICULA { get; set; }
    }
}
