//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.Dominio.Models.Temporal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNEG_RESULTADOS
    {
        public int RES_ID { get; set; }
        public Nullable<int> MAT_ID { get; set; }
        public Nullable<int> ASD_ID { get; set; }
        public int RES_DEBERES { get; set; }
        public int RES_EXAMEN { get; set; }
        public System.DateTime RES_FECHA { get; set; }
    
        public virtual AsignacionDocente TNEG_ASIGNACION_DOCENTE { get; set; }
        public virtual Matricula TNEG_MATRICULA { get; set; }
    }
}
