//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.Dominio.Models.Temporal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNEG_ASIGNACION_DOCENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TNEG_ASIGNACION_DOCENTE()
        {
            this.TNEG_RESULTADOS = new HashSet<TNEG_RESULTADOS>();
        }
    
        public int ASD_ID { get; set; }
        public Nullable<int> USR_ROL_ID { get; set; }
        public Nullable<int> COE_ID { get; set; }
        public System.DateTime ASD_FECHA { get; set; }
    
        public virtual TNEG_COMPONENTE_EDUCATIVO TNEG_COMPONENTE_EDUCATIVO { get; set; }
        public virtual TSEG_USUARIO_ROL TSEG_USUARIO_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNEG_RESULTADOS> TNEG_RESULTADOS { get; set; }
    }
}
