//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.Dominio.Models.Temporal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSEG_USUARIO_ROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSEG_USUARIO_ROL()
        {
            this.TNEG_ASIGNACION_DOCENTE = new HashSet<AsignacionDocente>();
            this.TNEG_MATRICULA = new HashSet<Matricula>();
        }
    
        public int USR_ROL_ID { get; set; }
        public int ROL_ID { get; set; }
        public int USR_ID { get; set; }
        public int VERSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionDocente> TNEG_ASIGNACION_DOCENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> TNEG_MATRICULA { get; set; }
    }
}
