//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos.Web {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recursos.Web.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización Exitosa.
        /// </summary>
        public static string ActualizacionExitosa {
            get {
                return ResourceManager.GetString("ActualizacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase extra ha sido eliminada satisfactoriamente..
        /// </summary>
        public static string AgendaClasesExtra_Delete_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("AgendaClasesExtra_Delete_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar la entidad. Intente nuevamente..
        /// </summary>
        public static string AgendaClasesExtra_Delete_ErrorMessage {
            get {
                return ResourceManager.GetString("AgendaClasesExtra_Delete_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase extra ha sido guardada satisfactoriamente..
        /// </summary>
        public static string AgendaClasesExtra_EditionSave_SavedSuccessfully {
            get {
                return ResourceManager.GetString("AgendaClasesExtra_EditionSave_SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron coincidencias con su búsqueda..
        /// </summary>
        public static string AgendaClasesExtra_Index_NoRecordsFound {
            get {
                return ResourceManager.GetString("AgendaClasesExtra_Index_NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted registró su asistencia pasados los {0} minutos de inicio de clases, por lo que se registrará una advertencia sobre la hora de ingreso.
        /// </summary>
        public static string AgendaInicioSesionConAdvertencia {
            get {
                return ResourceManager.GetString("AgendaInicioSesionConAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Clase exitoso.
        /// </summary>
        public static string AgendaInicioSesionExitoso {
            get {
                return ResourceManager.GetString("AgendaInicioSesionExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede iniciar su clase, no tiene alumnos inscritos..
        /// </summary>
        public static string AgendaInicioSesionSinAlumnos {
            get {
                return ResourceManager.GetString("AgendaInicioSesionSinAlumnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0}, modifica diario temático para: {1}.
        /// </summary>
        public static string AuditoriaEditarDiarioTematico {
            get {
                return ResourceManager.GetString("AuditoriaEditarDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0}, registra diario temático para: {1}.
        /// </summary>
        public static string AuditoriaRegistrarDiarioTematico {
            get {
                return ResourceManager.GetString("AuditoriaRegistrarDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo  Id Alumno Banner es Requerido.
        /// </summary>
        public static string CampoIdAlumnoBanner {
            get {
                return ResourceManager.GetString("CampoIdAlumnoBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo NRC es Requerido.
        /// </summary>
        public static string CampoNRC {
            get {
                return ResourceManager.GetString("CampoNRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo Periodo es Requerido.
        /// </summary>
        public static string CampoPeriodo {
            get {
                return ResourceManager.GetString("CampoPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una clase extra registrada con los mismos datos.
        /// </summary>
        public static string ClaseExtraViewModel_Duplicated_ErrorMessage {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Duplicated_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de fecha no válida..
        /// </summary>
        public static string ClaseExtraViewModel_Fecha_Range_ErrorMessage {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Fecha_Range_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing application setting &apos;{0}&apos;.
        /// </summary>
        public static string ConfigurationErrors_MissingApplicationSetting_ErrorMessage {
            get {
                return ResourceManager.GetString("ConfigurationErrors_MissingApplicationSetting_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea registrar la asistencia?.
        /// </summary>
        public static string Confirmacion_Registro_Asistencia {
            get {
                return ResourceManager.GetString("Confirmacion_Registro_Asistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El alumno no presenta registros de asistencia..
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_NoRecordsFound {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de cédula incorrecta..
        /// </summary>
        public static string Consultas_AsistenciasEstudiante_WrongIdErrorMessage {
            get {
                return ResourceManager.GetString("Consultas_AsistenciasEstudiante_WrongIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene registro de asistencias..
        /// </summary>
        public static string Consultas_MisAsistencias_WrongIdErrorMessage {
            get {
                return ResourceManager.GetString("Consultas_MisAsistencias_WrongIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de acceso: rol de usuario incorrecto..
        /// </summary>
        public static string Consultas_MisAsistencias_WrongRoleErrorMessage {
            get {
                return ResourceManager.GetString("Consultas_MisAsistencias_WrongRoleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de acceso: usuario incorrecto..
        /// </summary>
        public static string Consultas_MisAsistencias_WrongUserErrorMessage {
            get {
                return ResourceManager.GetString("Consultas_MisAsistencias_WrongUserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres no permitidos.
        /// </summary>
        public static string DataTypeAttribute_CaracterEspecialValidationError {
            get {
                return ResourceManager.GetString("DataTypeAttribute_CaracterEspecialValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser una fecha..
        /// </summary>
        public static string DataTypeAttribute_DateValidationError {
            get {
                return ResourceManager.GetString("DataTypeAttribute_DateValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario autenticado no cuenta con agendas asociadas.
        /// </summary>
        public static string DocenteActual_WrongId_ErrorMessage {
            get {
                return ResourceManager.GetString("DocenteActual_WrongId_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted no posee Agenda desde este instante hasta el término del día de hoy {0}..
        /// </summary>
        public static string DocenteNoPoseeAgenda {
            get {
                return ResourceManager.GetString("DocenteNoPoseeAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe un inconveniente, vuelva a intentar más tarde.
        /// </summary>
        public static string ErrorGenerico {
            get {
                return ResourceManager.GetString("ErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe proceso en Ejecución, espere a que termine el mismo para ejecutar otro proceso..
        /// </summary>
        public static string ExisteProcesoPendienteGradebook {
            get {
                return ResourceManager.GetString("ExisteProcesoPendienteGradebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalización de clases fue exitoso para los modulos horarios: {0}.
        /// </summary>
        public static string FinalizarSesionExitoso {
            get {
                return ResourceManager.GetString("FinalizarSesionExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se Finalizó ninguna clase debido a que no está dentro del rango de finalización permitido.
        /// </summary>
        public static string FinalizarSesionNoSatisfactoriaFueraDeRango {
            get {
                return ResourceManager.GetString("FinalizarSesionNoSatisfactoriaFueraDeRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha iniciado clase o aun no Registra Asistencia de Alumnos, por lo tanto no puede Finalizar.
        /// </summary>
        public static string FinalizarSesionNoSatisfactoriaPrecondiciones {
            get {
                return ResourceManager.GetString("FinalizarSesionNoSatisfactoriaPrecondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede Finalizar Clase debido a que no está dentro del tiempo permitido.
        /// </summary>
        public static string FinalizarSesionNoSatisfactoriaTiempoPermitido {
            get {
                return ResourceManager.GetString("FinalizarSesionNoSatisfactoriaTiempoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Usuario con la misma Identificación ó Cuenta.
        /// </summary>
        public static string GestionUsuariosUsuarioDuplicado {
            get {
                return ResourceManager.GetString("GestionUsuariosUsuarioDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario eliminado exitosamente.
        /// </summary>
        public static string GestionUsuariosUsuarioEliminadoCorrecto {
            get {
                return ResourceManager.GetString("GestionUsuariosUsuarioEliminadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario guardado exitosamente.
        /// </summary>
        public static string GestionUsuariosUsuarioGuardadoCorrecto {
            get {
                return ResourceManager.GetString("GestionUsuariosUsuarioGuardadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su Diario Temático se ha guardado correctamente..
        /// </summary>
        public static string GuardarCorrectoDiarioTematico {
            get {
                return ResourceManager.GetString("GuardarCorrectoDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Campo Identificación es requerido.
        /// </summary>
        public static string IdentificacionRequerida {
            get {
                return ResourceManager.GetString("IdentificacionRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted intentó registrar su asistencia fuera del tiempo máximo de ingreso permitido. Su asistencia no será registrada en el sistema.
        /// </summary>
        public static string InicioSesionNoPermitido {
            get {
                return ResourceManager.GetString("InicioSesionNoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser un tipo de cadena o matriz con una longitud máxima de &apos;{1}&apos;..
        /// </summary>
        public static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para la búsqueda propuesta no existe resultados.
        /// </summary>
        public static string No_Existe_Resultado_Busqueda {
            get {
                return ResourceManager.GetString("No_Existe_Resultado_Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron resultados para la búsqueda propuesta.
        /// </summary>
        public static string NoFoundRecordsMessage {
            get {
                return ResourceManager.GetString("NoFoundRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos una inasistencia..
        /// </summary>
        public static string NoSelectedAbsences_ErrorMessage {
            get {
                return ResourceManager.GetString("NoSelectedAbsences_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso de Cálculo de Notas enviado a ejecutar exitosamente, verifique el estado del mismo..
        /// </summary>
        public static string ProcesoEnviadoEjecutarGradebook {
            get {
                return ResourceManager.GetString("ProcesoEnviadoEjecutarGradebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe estar entre {1} y {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistencia de alumnos registrada con éxito.
        /// </summary>
        public static string RegistroAsistenciaAlumnosExito {
            get {
                return ResourceManager.GetString("RegistroAsistenciaAlumnosExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha final no debe ser inferior a la fecha inicial..
        /// </summary>
        public static string ReporteCargaHorariaViewMode_FechaFin_CompareError {
            get {
                return ResourceManager.GetString("ReporteCargaHorariaViewMode_FechaFin_CompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es obligatorio..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para visualizar sus diarios temáticos es necesario registrar asistencia a sus Estudiantes, además se debe considerar que tiene un plazo de {0} días a partir del evento de su inicio de clases para registrarlo..
        /// </summary>
        public static string VisualizarDiarioTematico {
            get {
                return ResourceManager.GetString("VisualizarDiarioTematico", resourceCulture);
            }
        }
    }
}
