//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos.Web {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titulos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titulos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recursos.Web.Titulos", typeof(Titulos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string AccionDiarioTematico {
            get {
                return ResourceManager.GetString("AccionDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar y regresar a la lista de actividades extras.
        /// </summary>
        public static string AgendaClaseExtra_Button_Cancel {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string AgendaClaseExtra_Button_Close {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una nueva actividad extra.
        /// </summary>
        public static string AgendaClaseExtra_Button_Create {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar!!!.
        /// </summary>
        public static string AgendaClaseExtra_Button_Delete {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar la actividad extra.
        /// </summary>
        public static string AgendaClaseExtra_Button_Edit {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar a la lista de actividades extras.
        /// </summary>
        public static string AgendaClaseExtra_Button_Index {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Button_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string AgendaClaseExtra_Button_Save {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string AgendaClaseExtra_Button_Search {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string AgendaClaseExtra_Confirmation_No {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Confirmation_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerde que las horas extraordinarias serán pagadas al docente. Esta seguro que desea guardar los datos?..
        /// </summary>
        public static string AgendaClaseExtra_Confirmation_Text {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Confirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        public static string AgendaClaseExtra_Confirmation_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        public static string AgendaClaseExtra_Confirmation_Yes {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Confirmation_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva actividad extra.
        /// </summary>
        public static string AgendaClaseExtra_Create_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme para eliminar la actividad extra..
        /// </summary>
        public static string AgendaClaseExtra_Delete_Confirmation_Text {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Delete_Confirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme eliminación.
        /// </summary>
        public static string AgendaClaseExtra_Delete_Confirmation_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Delete_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de actividad extra.
        /// </summary>
        public static string AgendaClaseExtra_Details_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar actividad extra.
        /// </summary>
        public static string AgendaClaseExtra_Edit_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividades Extras.
        /// </summary>
        public static string AgendaClaseExtra_Index_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva.
        /// </summary>
        public static string AgendaClaseExtra_Link_Create {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Link_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva actividad extra.
        /// </summary>
        public static string AgendaClaseExtra_Link_Create_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Link_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar....
        /// </summary>
        public static string AgendaClaseExtra_Link_Delete {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Link_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AgendaClaseExtra_Link_Details {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Link_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string AgendaClaseExtra_Link_Details_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Link_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AgendaClaseExtra_Link_Edit {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Link_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string AgendaClaseExtra_Link_Edit_Title {
            get {
                return ResourceManager.GetString("AgendaClaseExtra_Link_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string AgendaClaseExtraViewModelItem_Asignatura_DisplayName {
            get {
                return ResourceManager.GetString("AgendaClaseExtraViewModelItem_Asignatura_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escuela.
        /// </summary>
        public static string AgendaClaseExtraViewModelItem_Escuela_DisplayName {
            get {
                return ResourceManager.GetString("AgendaClaseExtraViewModelItem_Escuela_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string AgendaClaseExtraViewModelItem_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("AgendaClaseExtraViewModelItem_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Docente.
        /// </summary>
        public static string AgendaClaseExtraViewModelItem_Identificación_DisplayName {
            get {
                return ResourceManager.GetString("AgendaClaseExtraViewModelItem_Identificación_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Clases.
        /// </summary>
        public static string AgendaClaseExtraViewModelItem_NúmeroClases_DisplayName {
            get {
                return ResourceManager.GetString("AgendaClaseExtraViewModelItem_NúmeroClases_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paralelo.
        /// </summary>
        public static string AgendaClaseExtraViewModelItem_Paralelo_DisplayName {
            get {
                return ResourceManager.GetString("AgendaClaseExtraViewModelItem_Paralelo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string AsignaturaDiarioTematico {
            get {
                return ResourceManager.GetString("AsignaturaDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string AsistenciaEstudianteItem_Asignatura_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaEstudianteItem_Asignatura_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aula.
        /// </summary>
        public static string AsistenciaEstudianteItem_Aula_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaEstudianteItem_Aula_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string AsistenciaEstudianteItem_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaEstudianteItem_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Fin.
        /// </summary>
        public static string AsistenciaEstudianteItem_HoraFin_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaEstudianteItem_HoraFin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Inicio.
        /// </summary>
        public static string AsistenciaEstudianteItem_HoraInicio_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaEstudianteItem_HoraInicio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistencia de Estudiantes.
        /// </summary>
        public static string AsistenciaEstudiantes {
            get {
                return ResourceManager.GetString("AsistenciaEstudiantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string AsistenciaMasivaItem_Asignatura_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaMasivaItem_Asignatura_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aula.
        /// </summary>
        public static string AsistenciaMasivaItem_Aula_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaMasivaItem_Aula_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campus.
        /// </summary>
        public static string AsistenciaMasivaItem_Campus_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaMasivaItem_Campus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula.
        /// </summary>
        public static string AsistenciaMasivaItem_EstudianteCedula_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaMasivaItem_EstudianteCedula_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string AsistenciaMasivaItem_EstudianteId_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaMasivaItem_EstudianteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string AsistenciaMasivaItem_EstudianteNombreCompleto_DisplayName {
            get {
                return ResourceManager.GetString("AsistenciaMasivaItem_EstudianteNombreCompleto_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NRC: {0}.
        /// </summary>
        public static string AsistenciaMasivaItem_Nrc_DisplayFormat {
            get {
                return ResourceManager.GetString("AsistenciaMasivaItem_Nrc_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros de Auditoría.
        /// </summary>
        public static string Auditoria_PageTitle {
            get {
                return ResourceManager.GetString("Auditoria_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción:.
        /// </summary>
        public static string AuditoriaCriteria_Accion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Accion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha hasta:.
        /// </summary>
        public static string AuditoriaCriteria_FechaFinal_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_FechaFinal_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha desde:.
        /// </summary>
        public static string AuditoriaCriteria_FechaInicio_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_FechaInicio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad:.
        /// </summary>
        public static string AuditoriaCriteria_Funcionalidad_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Funcionalidad_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación:.
        /// </summary>
        public static string AuditoriaCriteria_Identificador_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Identificador_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        public static string AuditoriaCriteria_Usuario_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaCriteria_Usuario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string AuditoriaItem_Accion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Accion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string AuditoriaItem_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad.
        /// </summary>
        public static string AuditoriaItem_Funcionalidad_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Funcionalidad_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string AuditoriaItem_Identificacion_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Identificacion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string AuditoriaItem_Registro_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Registro_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string AuditoriaItem_Usuario_DisplayName {
            get {
                return ResourceManager.GetString("AuditoriaItem_Usuario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva.
        /// </summary>
        public static string Button_NewF {
            get {
                return ResourceManager.GetString("Button_NewF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calcular Notas Asistencia Estudiante.
        /// </summary>
        public static string CalculoNotasAsistencia {
            get {
                return ResourceManager.GetString("CalculoNotasAsistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura:.
        /// </summary>
        public static string ClaseExtraViewModel_Asignatura_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Asignatura_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Docente:.
        /// </summary>
        public static string ClaseExtraViewModel_DocenteId_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_DocenteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre, id, cédula o pasaporte.
        /// </summary>
        public static string ClaseExtraViewModel_DocenteId_DisplayPrompt {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_DocenteId_DisplayPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escuela:.
        /// </summary>
        public static string ClaseExtraViewModel_Escuela_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Escuela_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        public static string ClaseExtraViewModel_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NRC:.
        /// </summary>
        public static string ClaseExtraViewModel_Nrc_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Nrc_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones:.
        /// </summary>
        public static string ClaseExtraViewModel_Observaciones_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Observaciones_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paralelo:.
        /// </summary>
        public static string ClaseExtraViewModel_Paralelo_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Paralelo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo:.
        /// </summary>
        public static string ClaseExtraViewModel_Periodo_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Periodo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de clases:.
        /// </summary>
        public static string ClaseExtraViewModel_Sesiones_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_Sesiones_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase extra.
        /// </summary>
        public static string ClaseExtraViewModel_TipoActividad_1 {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel.TipoActividad_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo actividad:.
        /// </summary>
        public static string ClaseExtraViewModel_TipoActividadId_DisplayName {
            get {
                return ResourceManager.GetString("ClaseExtraViewModel_TipoActividadId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        public static string Confirmacion_Mensajes {
            get {
                return ResourceManager.GetString("Confirmacion_Mensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de asistencia de estudiantes.
        /// </summary>
        public static string ConsultaAsistenciasEstudiante_Title {
            get {
                return ResourceManager.GetString("ConsultaAsistenciasEstudiante_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de asistencia de estudiante {0} ({1}) ({2}).
        /// </summary>
        public static string ConsultaAsistenciasEstudianteDetalles_TitleFormat {
            get {
                return ResourceManager.GetString("ConsultaAsistenciasEstudianteDetalles_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la asignatura:.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Asignatura_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Asignatura_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Asignatura_Grilla_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Asignatura_Grilla_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistencias.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Asistencias_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Asistencias_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a detalles....
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Button_Details {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Button_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula del estudiante:.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Cedula_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Cedula_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula:.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Cedula_DisplayShortName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Cedula_DisplayShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de asignatura:.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_CodigoAsignatura_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_CodigoAsignatura_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Docente.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Docente_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Docente_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Estudiante:.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_EstudianteId_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_EstudianteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltas.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Faltas_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Faltas_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horario.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Horario_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Horario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador Curso.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Identificador_Curso_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Identificador_Curso_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inasistencia.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Inasistencia_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Inasistencia_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificada.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_InasistenciaJustificada_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_InasistenciaJustificada_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inasistencias.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Inasistencias_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Inasistencias_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inasistencias justificadas.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_InasistenciasJustificadas_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_InasistenciasJustificadas_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Nombre_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Nombre_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NRC.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Nrc_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Nrc_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Numero_Detalle_Faltas_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Numero_Detalle_Faltas_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Periodo_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Periodo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % de faltas.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Porciento_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Porciento_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clases dictadas.
        /// </summary>
        public static string Consultas_AsistenciaEstudiante_Total_DisplayName {
            get {
                return ResourceManager.GetString("Consultas_AsistenciaEstudiante_Total_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterios Ejecución de Proceso.
        /// </summary>
        public static string CriteriosEjecuciionGradebook {
            get {
                return ResourceManager.GetString("CriteriosEjecuciionGradebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso.
        /// </summary>
        public static string CursoDiarioTematico {
            get {
                return ResourceManager.GetString("CursoDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día.
        /// </summary>
        public static string DiaDiarioTematico {
            get {
                return ResourceManager.GetString("DiaDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sus Diarios Temáticos Pendientes de Registro.
        /// </summary>
        public static string DiariosTematicosPendientes {
            get {
                return ResourceManager.GetString("DiariosTematicosPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Diario Temático.
        /// </summary>
        public static string DiarioTematicoEditar {
            get {
                return ResourceManager.GetString("DiarioTematicoEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Diario Temático.
        /// </summary>
        public static string DiarioTematicoRegistrar {
            get {
                return ResourceManager.GetString("DiarioTematicoRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha actual.
        /// </summary>
        public static string General_CurrentDate {
            get {
                return ResourceManager.GetString("General_CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string General_Date {
            get {
                return ResourceManager.GetString("General_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string General_FullName {
            get {
                return ResourceManager.GetString("General_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string General_Identification {
            get {
                return ResourceManager.GetString("General_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulo.
        /// </summary>
        public static string General_Module {
            get {
                return ResourceManager.GetString("General_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han ingresado los campos obligatorios o existen datos no válidos.
        /// </summary>
        public static string General_ValidationSummary_Message {
            get {
                return ResourceManager.GetString("General_ValidationSummary_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agenda Docente.
        /// </summary>
        public static string HorarioDocente {
            get {
                return ResourceManager.GetString("HorarioDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador Curso.
        /// </summary>
        public static string IdentificadorCursoDiarioTematico {
            get {
                return ResourceManager.GetString("IdentificadorCursoDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string InasistenciaMasivaDocenteItem_Asignatura_DisplayName {
            get {
                return ResourceManager.GetString("InasistenciaMasivaDocenteItem_Asignatura_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aula.
        /// </summary>
        public static string InasistenciaMasivaDocenteItem_Aula_DisplayName {
            get {
                return ResourceManager.GetString("InasistenciaMasivaDocenteItem_Aula_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campus: {0}.
        /// </summary>
        public static string InasistenciaMasivaDocenteItem_Campus_DisplayGroupName {
            get {
                return ResourceManager.GetString("InasistenciaMasivaDocenteItem_Campus_DisplayGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula.
        /// </summary>
        public static string InasistenciaMasivaDocenteItem_DocenteCI_DisplayName {
            get {
                return ResourceManager.GetString("InasistenciaMasivaDocenteItem_DocenteCI_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string InasistenciaMasivaDocenteItem_DocenteNombreCompleto_DisplayName {
            get {
                return ResourceManager.GetString("InasistenciaMasivaDocenteItem_DocenteNombreCompleto_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NRC.
        /// </summary>
        public static string InasistenciaMasivaDocenteItem_Nrc_DisplayName {
            get {
                return ResourceManager.GetString("InasistenciaMasivaDocenteItem_Nrc_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paralelo.
        /// </summary>
        public static string InasistenciaMasivaDocenteItem_Paralelo_DisplayName {
            get {
                return ResourceManager.GetString("InasistenciaMasivaDocenteItem_Paralelo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado último proceso de Gradebook.
        /// </summary>
        public static string InformacionUltimoProcesoGradebook {
            get {
                return ResourceManager.GetString("InformacionUltimoProcesoGradebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serán justificadas {0} inasistencias:.
        /// </summary>
        public static string Justificacion_Absences_Format {
            get {
                return ResourceManager.GetString("Justificacion_Absences_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las siguientes inasistencias serán justificadas.
        /// </summary>
        public static string Justificacion_Absences_Header {
            get {
                return ResourceManager.GetString("Justificacion_Absences_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerde que al justificar esta(s) inasistencia(s), también se creará un registro de inasistencia para los estudiantes, el cual deberá ser justificado..
        /// </summary>
        public static string Justificacion_Absences_Warning {
            get {
                return ResourceManager.GetString("Justificacion_Absences_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificar.
        /// </summary>
        public static string Justificacion_Button_Justify {
            get {
                return ResourceManager.GetString("Justificacion_Button_Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificar todas.
        /// </summary>
        public static string Justificacion_Button_JustifyAll {
            get {
                return ResourceManager.GetString("Justificacion_Button_JustifyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificar seleccionadas.
        /// </summary>
        public static string Justificacion_Button_JustifySelection {
            get {
                return ResourceManager.GetString("Justificacion_Button_JustifySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme los datos de las inasistencias a justificar.
        /// </summary>
        public static string Justificacion_Confirmation_Header {
            get {
                return ResourceManager.GetString("Justificacion_Confirmation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llenar los siguientes datos para justificar.
        /// </summary>
        public static string Justificacion_DataForm_Legend {
            get {
                return ResourceManager.GetString("Justificacion_DataForm_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para justificar las inasistencias del docente, debe marcar los checklist y presionar el botón “Justificar seleccionados”..
        /// </summary>
        public static string Justificacion_Docente_Individual_Justify_Info {
            get {
                return ResourceManager.GetString("Justificacion_Docente_Individual_Justify_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para justificar las inasistencias del docente, debe marcar los checklist y presionar el botón “Justificar seleccionados”. Si desea justificar la falta a todos los docentes debe presionar el botón “Justificar todas”, sin marcar ninguno de los checks..
        /// </summary>
        public static string Justificacion_Docente_Masiva_Justify_Info {
            get {
                return ResourceManager.GetString("Justificacion_Docente_Masiva_Justify_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para justificar las inasistencias del estudiante, debe marcar los checklist y presionar el botón “Justificar seleccionados”..
        /// </summary>
        public static string Justificacion_Estudiante_Individual_Justify_Info {
            get {
                return ResourceManager.GetString("Justificacion_Estudiante_Individual_Justify_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para justificar las inasistencias del docente, debe marcar los checklist y presionar el botón “Justificar seleccionados”. Si desea justificar la falta a todos los estudiantes debe presionar el botón “Justificar todas”, sin marcar ninguno de los checks..
        /// </summary>
        public static string Justificacion_Estudiante_Masiva_Justify_Info {
            get {
                return ResourceManager.GetString("Justificacion_Estudiante_Masiva_Justify_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encontrado(s) {0} registro(s)..
        /// </summary>
        public static string Justificacion_FoundRecords_Format {
            get {
                return ResourceManager.GetString("Justificacion_FoundRecords_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar inasistencia.
        /// </summary>
        public static string Justificacion_Selection_Legend {
            get {
                return ResourceManager.GetString("Justificacion_Selection_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación de inasistencia del docente realizada exitosamente.
        /// </summary>
        public static string JustificacionDocente_Individual_CompletedMessage {
            get {
                return ResourceManager.GetString("JustificacionDocente_Individual_CompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación Individual de docentes.
        /// </summary>
        public static string JustificacionDocente_Individual_Title {
            get {
                return ResourceManager.GetString("JustificacionDocente_Individual_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación de inasistencias realizada exitosamente.
        /// </summary>
        public static string JustificacionDocente_Masiva_CompletedMessage {
            get {
                return ResourceManager.GetString("JustificacionDocente_Masiva_CompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación masiva de docentes.
        /// </summary>
        public static string JustificacionDocente_Masiva_Title {
            get {
                return ResourceManager.GetString("JustificacionDocente_Masiva_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        public static string JustificacionDocenteFiltrosIndividual_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteFiltrosIndividual_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación:.
        /// </summary>
        public static string JustificacionDocenteFiltrosIndividual_Identificacion_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteFiltrosIndividual_Identificacion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizado por:.
        /// </summary>
        public static string JustificacionDocenteIndividualDataViewModel_AuthorizedBy_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteIndividualDataViewModel_AuthorizedBy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia:.
        /// </summary>
        public static string JustificacionDocenteIndividualDataViewModel_Reference_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteIndividualDataViewModel_Reference_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación:.
        /// </summary>
        public static string JustificacionDocenteIndividualDataViewModel_Remarks_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteIndividualDataViewModel_Remarks_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo:.
        /// </summary>
        public static string JustificacionDocenteIndividualDataViewModel_TipoMotivoId_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteIndividualDataViewModel_TipoMotivoId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizado por:.
        /// </summary>
        public static string JustificacionDocenteMasivaDataViewModel_AuthorizedBy_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteMasivaDataViewModel_AuthorizedBy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia:.
        /// </summary>
        public static string JustificacionDocenteMasivaDataViewModel_Reference_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteMasivaDataViewModel_Reference_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación:.
        /// </summary>
        public static string JustificacionDocenteMasivaDataViewModel_Remarks_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteMasivaDataViewModel_Remarks_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo:.
        /// </summary>
        public static string JustificacionDocenteMasivaDataViewModel_TipoMotivoId_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteMasivaDataViewModel_TipoMotivoId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campus:.
        /// </summary>
        public static string JustificacionDocenteMasivaViewModel_Campus_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteMasivaViewModel_Campus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        public static string JustificacionDocenteMasivaViewModel_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteMasivaViewModel_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NRC:.
        /// </summary>
        public static string JustificacionDocenteMasivaViewModel_Nrc_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteMasivaViewModel_Nrc_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Módulos:.
        /// </summary>
        public static string JustificacionDocenteMasivaViewModel_RangoModulos_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteMasivaViewModel_RangoModulos_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignatura.
        /// </summary>
        public static string JustificacionDocenteResultadosIndividual_Asignatura_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteResultadosIndividual_Asignatura_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aula.
        /// </summary>
        public static string JustificacionDocenteResultadosIndividual_Aula_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteResultadosIndividual_Aula_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Fin.
        /// </summary>
        public static string JustificacionDocenteResultadosIndividual_HoraFin_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteResultadosIndividual_HoraFin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Inicio.
        /// </summary>
        public static string JustificacionDocenteResultadosIndividual_HoraInicio_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteResultadosIndividual_HoraInicio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección.
        /// </summary>
        public static string JustificacionDocenteResultadosIndividual_Seleccion_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionDocenteResultadosIndividual_Seleccion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación de inasistencia del estudiante realizada exitosamente.
        /// </summary>
        public static string JustificacionEstudiante_Individual_CompletedMessage {
            get {
                return ResourceManager.GetString("JustificacionEstudiante_Individual_CompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación Individual de estudiantes.
        /// </summary>
        public static string JustificacionEstudiante_Individual_Title {
            get {
                return ResourceManager.GetString("JustificacionEstudiante_Individual_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación de inasistencias realizada exitosamente.
        /// </summary>
        public static string JustificacionEstudiante_Masiva_CompletedMessage {
            get {
                return ResourceManager.GetString("JustificacionEstudiante_Masiva_CompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación masiva de estudiantes.
        /// </summary>
        public static string JustificacionEstudiante_Masiva_Title {
            get {
                return ResourceManager.GetString("JustificacionEstudiante_Masiva_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizado por:.
        /// </summary>
        public static string JustificacionEstudianteIndividualDataViewModel_AuthorizedBy_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteIndividualDataViewModel_AuthorizedBy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia:.
        /// </summary>
        public static string JustificacionEstudianteIndividualDataViewModel_Reference_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteIndividualDataViewModel_Reference_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación:.
        /// </summary>
        public static string JustificacionEstudianteIndividualDataViewModel_Remarks_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteIndividualDataViewModel_Remarks_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo:.
        /// </summary>
        public static string JustificacionEstudianteIndividualDataViewModel_TipoMotivoId_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteIndividualDataViewModel_TipoMotivoId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación del estudiante (Banner id):.
        /// </summary>
        public static string JustificacionEstudianteIndividualViewModel_EstudianteId_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteIndividualViewModel_EstudianteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        public static string JustificacionEstudianteIndividualViewModel_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteIndividualViewModel_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizado por:.
        /// </summary>
        public static string JustificacionEstudianteMasivaDataViewModel_AuthorizedBy_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteMasivaDataViewModel_AuthorizedBy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia:.
        /// </summary>
        public static string JustificacionEstudianteMasivaDataViewModel_Reference_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteMasivaDataViewModel_Reference_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación:.
        /// </summary>
        public static string JustificacionEstudianteMasivaDataViewModel_Remarks_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteMasivaDataViewModel_Remarks_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo:.
        /// </summary>
        public static string JustificacionEstudianteMasivaDataViewModel_TipoMotivoId_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteMasivaDataViewModel_TipoMotivoId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campus:.
        /// </summary>
        public static string JustificacionEstudianteMasivaViewModel_Campus_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteMasivaViewModel_Campus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        public static string JustificacionEstudianteMasivaViewModel_Fecha_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteMasivaViewModel_Fecha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NRC:.
        /// </summary>
        public static string JustificacionEstudianteMasivaViewModel_Nrc_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteMasivaViewModel_Nrc_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Módulos:.
        /// </summary>
        public static string JustificacionEstudianteMasivaViewModel_RangoModulos_DisplayName {
            get {
                return ResourceManager.GetString("JustificacionEstudianteMasivaViewModel_RangoModulos_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperaciones de docentes.
        /// </summary>
        public static string LinkRecuperacionClases {
            get {
                return ResourceManager.GetString("LinkRecuperacionClases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.apellido@udla.edu.ec.
        /// </summary>
        public static string LoginMarcaAguaEjemplo {
            get {
                return ResourceManager.GetString("LoginMarcaAguaEjemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NRC.
        /// </summary>
        public static string NRC {
            get {
                return ResourceManager.GetString("NRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Alumnos: .
        /// </summary>
        public static string NumeroAlumnosRegistroAsistencia {
            get {
                return ResourceManager.GetString("NumeroAlumnosRegistroAsistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paralelo.
        /// </summary>
        public static string ParaleloDiarioTematico {
            get {
                return ResourceManager.GetString("ParaleloDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Período.
        /// </summary>
        public static string PeriodoDiarioTematico {
            get {
                return ResourceManager.GetString("PeriodoDiarioTematico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta:.
        /// </summary>
        public static string ReporteAcotadoViewModel_FechaFin_DisplayName {
            get {
                return ResourceManager.GetString("ReporteAcotadoViewModel_FechaFin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde:.
        /// </summary>
        public static string ReporteAcotadoViewModel_FechaInicio_DisplayName {
            get {
                return ResourceManager.GetString("ReporteAcotadoViewModel_FechaInicio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Asistencia del docente.
        /// </summary>
        public static string ReporteAsistenciasDocente_Title {
            get {
                return ResourceManager.GetString("ReporteAsistenciasDocente_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Asistencias de estudiantes.
        /// </summary>
        public static string ReporteAsistenciasEstudiantes_Title {
            get {
                return ResourceManager.GetString("ReporteAsistenciasEstudiantes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área:.
        /// </summary>
        public static string ReporteAsistenciasEstudiantesViewMode_AreaId_DisplayName {
            get {
                return ResourceManager.GetString("ReporteAsistenciasEstudiantesViewMode_AreaId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facultad:.
        /// </summary>
        public static string ReporteAsistenciasEstudiantesViewMode_FacultadId_DisplayName {
            get {
                return ResourceManager.GetString("ReporteAsistenciasEstudiantesViewMode_FacultadId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo:.
        /// </summary>
        public static string ReporteAsistenciasEstudiantesViewMode_PeriodoId_DisplayName {
            get {
                return ResourceManager.GetString("ReporteAsistenciasEstudiantesViewMode_PeriodoId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Carga Horaria.
        /// </summary>
        public static string ReporteCargaHoraria_Title {
            get {
                return ResourceManager.GetString("ReporteCargaHoraria_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación del docente:.
        /// </summary>
        public static string ReporteDocenteViewMode_DocenteId_DisplayName {
            get {
                return ResourceManager.GetString("ReporteDocenteViewMode_DocenteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación del estudiante:.
        /// </summary>
        public static string ReporteEstudianteViewMode_EstudianteId_DisplayName {
            get {
                return ResourceManager.GetString("ReporteEstudianteViewMode_EstudianteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área:.
        /// </summary>
        public static string ReporteNovedadDocenteViewModel_CodArea_DisplayName {
            get {
                return ResourceManager.GetString("ReporteNovedadDocenteViewModel_CodArea_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código o Nombre.
        /// </summary>
        public static string ReporteNovedadDocenteViewModel_CodArea_DisplayPrompt {
            get {
                return ResourceManager.GetString("ReporteNovedadDocenteViewModel_CodArea_DisplayPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres Válidos:.
        /// </summary>
        public static string ReporteNovedadDocenteViewModel_CodCaracteresValidos_DisplayName {
            get {
                return ResourceManager.GetString("ReporteNovedadDocenteViewModel_CodCaracteresValidos_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código o Nombre.
        /// </summary>
        public static string ReporteNovedadDocenteViewModel_CodCaracteresValidos_DisplayPrompt {
            get {
                return ResourceManager.GetString("ReporteNovedadDocenteViewModel_CodCaracteresValidos_DisplayPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Novedades del Docente.
        /// </summary>
        public static string ReporteNovedadesDocente {
            get {
                return ResourceManager.GetString("ReporteNovedadesDocente", resourceCulture);
            }
        }
    }
}
