---TSEG_MENU

--INSERT [dbo].[TSEG_MENU] ([SIS_ID], [MEN_CODIGO], [MEN_NOMBRE], [MEN_DESCRIPCION],[VERSION]) VALUES ((SELECT SIS_ID FROM [TSEG_SISTEMA] WHERE SIS_CODIGO='SISTEMASIS'),N'SISMENMAIN', N'Menú Principal SIS', N'Menú Principal SIS', 1);

---TSEG_MENUSITEM

--CONFIGURACION
--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'CONFIGURNG',N'Configuraciones', N'Ítem contenedor que agrupa a sistema, roles, parámetros y sesión', N'#', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),1,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),NULL,NULL,1,1,N'ui-icon-settings');
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'Parametro',N'Parámetros', N'Parámetros', N'/parametrosistema', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',NULL,1,1,N'ui-icon-settings');
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'USUARIOS',N'Usuarios', N'Usuarios', N'/usuario', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMUSU' COLLATE DATABASE_DEFAULT),1,2,N'ui-icon-face');
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'Sistema',N'Sistema', N'Sistema', N'/sistema', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',NULL,1,3,N'ui-icon-system-update');
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'Roles',N'Roles', N'Roles', N'/rol', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',NULL,1,4,N'ui-icon-security');
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'Sesion',N'Sesión', N'Sesión', N'/sesion', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',NULL,1,5,N'ui-icon-book');
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'Auditoria',N'Auditoría', N'Auditoría', N'/auditoria', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',NULL,1,6,N'ui-icon-timeline');
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'Catalogo',N'Catálogo', N'Catálogo', N'/catalogo', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',NULL,1,7,N'ui-icon-receipt');	
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENMENU',N'Menu', N'Menu', N'/menu', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMUSU' COLLATE DATABASE_DEFAULT),1,8,N'ui-icon-menu');
	--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENFUNCIONALIDA',N'Funcionalidad', N'Funcionalidad', N'/funcionalidad', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'CONFIGURNG',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMINS' COLLATE DATABASE_DEFAULT),1,9,N'ui-icon-functions');

--ADMINISTRACION
--INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'ADMINISTRACION',N'Administración', N'Ítem contenedor que agrupa a Administración.', N'#', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),1,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),NULL,NULL,1,1,N'ui-icon-assignment-turned-in');
	INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENENCUESTA',N'Encuesta', N'Encuesta', N'/encuesta', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'ADMINISTRACION',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMENC' COLLATE DATABASE_DEFAULT),1,3,N'ui-icon-question-answer');
	INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENUNIVERSIDAD',N'Universidad', N'Universidad', N'/universidad', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'ADMINISTRACION',NULL,1,4,N'ui-icon-school');
	INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENPROGRAMA',N'Programa', N'Programa', N'/programa', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'ADMINISTRACION',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMPROGRA' COLLATE DATABASE_DEFAULT),1,5,N'ui-icon-class');
	INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENPERIOACAD',N'Periodo Academico', N'Periodo Academico', N'/periodoacademico', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'ADMINISTRACION',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMPERACA' COLLATE DATABASE_DEFAULT),1,6,N'ui-icon-timeline');
	INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENCENTRO',N'Centro', N'Centro', N'/centro', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'ADMINISTRACION',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMCEN' COLLATE DATABASE_DEFAULT),1,8,N'ui-icon-location-city');
	INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENADMUSUARIO',N'Usuario', N'Usuario', N'/universidadusuario', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'ADMINISTRACION',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMUSUUNI' COLLATE DATABASE_DEFAULT),1,9,N'ui-icon-face');
	INSERT [dbo].[TSEG_MENUSITEM] ([MIT_CODIGO], [MIT_NOMBRE], [MIT_DESCRIPCION], [MIT_URL],[MIT_ESTADOID],[MIT_TIPOID],[MEN_ID],[PADRE_CODIGO],[FUN_ID],[VERSION],[MIT_ORDEN],[MIT_ICONO]) VALUES (N'MENOFERTAPROGR',N'Oferta Programa', N'Oferta Programa', N'/ofertaprograma', (SELECT [ITM_ID] FROM [dbo].[TADM_ITEMCATALOGO] WHERE [ITM_CODIGO] = N'ESTENTACTI' COLLATE DATABASE_DEFAULT),2,(SELECT [MEN_ID] FROM [dbo].[TSEG_MENU] WHERE [MEN_CODIGO] = N'SISMENMAIN' COLLATE DATABASE_DEFAULT),'ADMINISTRACION',(SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMOFEPRO' COLLATE DATABASE_DEFAULT),1,10,N'ui-icon-extension');
	
----TADM_PARAMETROSISTEMA

--Periodos Academicos
/*INSERT [dbo].[TADM_PARAMETROSISTEMA] ([SIS_ID], [PAR_CODIGO], [PAR_NOMBRE], [PAR_DESCRIPCION],[PAR_CATEGORIAID],[PAR_TIPOID],[PAR_VALOR],[PAR_ESEDITABLE],[PAR_FECHA_CREACION],[PAR_FECHA_ACTUALIZACION],[PAR_USUARIO_CREACION_ID],[PAR_USUARIO_ACTUALIZACION_ID],[VERSION],[PAR_OPCIONES]) 
VALUES ((SELECT SIS_ID FROM [TSEG_SISTEMA] WHERE SIS_CODIGO='SISTEMASIS'),N'PARPERACA', N'Periodos Académicos', N'Periodos Académicos', 1,4,'-',1,GETDATE(),NULL,(SELECT [USR_ID] FROM [TSEG_USUARIO] WHERE [USR_Cuenta]='admin'),NULL,1,1);
	
	INSERT INTO [dbo].[TADM_PARAMETRO_OPCIONES]
           ([PAR_ID]
           ,[POP_VALOR]
           ,[POP_TEXTO]
           ,[VERSION])
     VALUES
           ((SELECT [PAR_ID]      
			  FROM [dbo].[TADM_PARAMETROSISTEMA]
			  WHERE PAR_CODIGO = 'PARPERACA')
           ,'Abril - Agosto 2018'
           ,'PERABRAGO'
           ,1);
		   
--Programas Academicos
INSERT [dbo].[TADM_PARAMETROSISTEMA] ([SIS_ID], [PAR_CODIGO], [PAR_NOMBRE], [PAR_DESCRIPCION],[PAR_CATEGORIAID],[PAR_TIPOID],[PAR_VALOR],[PAR_ESEDITABLE],[PAR_FECHA_CREACION],[PAR_FECHA_ACTUALIZACION],[PAR_USUARIO_CREACION_ID],[PAR_USUARIO_ACTUALIZACION_ID],[VERSION],[PAR_OPCIONES]) 
VALUES ((SELECT SIS_ID FROM [TSEG_SISTEMA] WHERE SIS_CODIGO='SISTEMASIS'),N'PARPROACA', N'Programas Académicos', N'Programas Académicos', 1,4,'-',1,GETDATE(),NULL,(SELECT [USR_ID] FROM [TSEG_USUARIO] WHERE [USR_Cuenta]='admin'),NULL,1,1);
	
	INSERT INTO [dbo].[TADM_PARAMETRO_OPCIONES]
           ([PAR_ID]
           ,[POP_VALOR]
           ,[POP_TEXTO]
           ,[VERSION])
     VALUES
           ((SELECT [PAR_ID]      
			  FROM [dbo].[TADM_PARAMETROSISTEMA]
			  WHERE PAR_CODIGO = 'PARPROACA')
           ,'Sistemas Informáticos'
           ,'PROSISTEMAS'
           ,1);
		   
--Centros
INSERT [dbo].[TADM_PARAMETROSISTEMA] ([SIS_ID], [PAR_CODIGO], [PAR_NOMBRE], [PAR_DESCRIPCION],[PAR_CATEGORIAID],[PAR_TIPOID],[PAR_VALOR],[PAR_ESEDITABLE],[PAR_FECHA_CREACION],[PAR_FECHA_ACTUALIZACION],[PAR_USUARIO_CREACION_ID],[PAR_USUARIO_ACTUALIZACION_ID],[VERSION],[PAR_OPCIONES]) 
VALUES ((SELECT SIS_ID FROM [TSEG_SISTEMA] WHERE SIS_CODIGO='SISTEMASIS'),N'PARCENTROS', N'Centros', N'Centros', 1,4,'-',1,GETDATE(),NULL,(SELECT [USR_ID] FROM [TSEG_USUARIO] WHERE [USR_Cuenta]='admin'),NULL,1,1);
	
	INSERT INTO [dbo].[TADM_PARAMETRO_OPCIONES]
           ([PAR_ID]
           ,[POP_VALOR]
           ,[POP_TEXTO]
           ,[VERSION])
     VALUES
           ((SELECT [PAR_ID]      
			  FROM [dbo].[TADM_PARAMETROSISTEMA]
			  WHERE PAR_CODIGO = 'PARCENTROS')
           ,'Loja'
           ,'CENLOJA'
           ,1);
		   
--Modulos
INSERT [dbo].[TADM_PARAMETROSISTEMA] ([SIS_ID], [PAR_CODIGO], [PAR_NOMBRE], [PAR_DESCRIPCION],[PAR_CATEGORIAID],[PAR_TIPOID],[PAR_VALOR],[PAR_ESEDITABLE],[PAR_FECHA_CREACION],[PAR_FECHA_ACTUALIZACION],[PAR_USUARIO_CREACION_ID],[PAR_USUARIO_ACTUALIZACION_ID],[VERSION],[PAR_OPCIONES]) 
VALUES ((SELECT SIS_ID FROM [TSEG_SISTEMA] WHERE SIS_CODIGO='SISTEMASIS'),N'PARMODULOS', N'Modulos', N'Modulos', 1,4,'-',1,GETDATE(),NULL,(SELECT [USR_ID] FROM [TSEG_USUARIO] WHERE [USR_Cuenta]='admin'),NULL,1,1);
	
	INSERT INTO [dbo].[TADM_PARAMETRO_OPCIONES]
           ([PAR_ID]
           ,[POP_VALOR]
           ,[POP_TEXTO]
           ,[VERSION])
     VALUES
           ((SELECT [PAR_ID]      
			  FROM [dbo].[TADM_PARAMETROSISTEMA]
			  WHERE PAR_CODIGO = 'PARMODULOS')
           ,'Modulo 1'
           ,'MODULO1'
           ,1);

		   */
