--Permisos
BEGIN  
	--Acciones CRUD 'VIEW','CREATE','EDIT','DELETE'
	DECLARE @rolAdministradorId int = (SELECT [ROL_ID] FROM [dbo].[TSEG_ROL] WHERE [ROL_CODIGO] = N'ADMUNIVER' COLLATE DATABASE_DEFAULT),
			@rolDocenteId int = (SELECT [ROL_ID] FROM [dbo].[TSEG_ROL] WHERE [ROL_CODIGO] = N'DOCENTE' COLLATE DATABASE_DEFAULT),
			@funu int = (SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMUSU' COLLATE DATABASE_DEFAULT),
			@funuu int = (SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMUSUUNI' COLLATE DATABASE_DEFAULT),
			@funp int = (SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMPROGRA' COLLATE DATABASE_DEFAULT),
			@funpa int = (SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMPERACA' COLLATE DATABASE_DEFAULT),
			@func int = (SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMCEN' COLLATE DATABASE_DEFAULT),
			@fune int = (SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMENC' COLLATE DATABASE_DEFAULT),
			@funop int = (SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMOFEPRO' COLLATE DATABASE_DEFAULT),
			@funr int = (SELECT [FUN_ID] FROM [dbo].[TSEG_FUNCIONALIDAD] WHERE [FUN_CODIGO] = N'FUNADMRES' COLLATE DATABASE_DEFAULT)

	--Administrador Universidad
	
	--Acceso a buscador de usuarios
	INSERT INTO [dbo].[TSEG_PERMISOS] ([ROL_ID],[ACC_ID],[PMI_NO_VISUALIZAR_MENU],[VERSION]) 
	VALUES( @rolAdministradorId, (SELECT [ACC_ID] FROM [dbo].[TSEG_ACCION] WHERE [FUN_ID] = @funu AND [ACC_CODIGO] = 'VIEW'),1,1 );
	
	--Acceso a todas las funcionalidades del negocio
	INSERT INTO [dbo].[TSEG_PERMISOS] ([ROL_ID],[ACC_ID],[PMI_NO_VISUALIZAR_MENU],[VERSION]) 
	SELECT @rolAdministradorId, [ACC_ID],0,1 FROM [dbo].[TSEG_ACCION]	WHERE [FUN_ID] = @funuu;

	INSERT INTO [dbo].[TSEG_PERMISOS] ([ROL_ID],[ACC_ID],[PMI_NO_VISUALIZAR_MENU],[VERSION]) 
	SELECT @rolAdministradorId, [ACC_ID],0,1 FROM [dbo].[TSEG_ACCION]	WHERE [FUN_ID] = @funp;

	INSERT INTO [dbo].[TSEG_PERMISOS] ([ROL_ID],[ACC_ID],[PMI_NO_VISUALIZAR_MENU],[VERSION]) 
	SELECT @rolAdministradorId, [ACC_ID],0,1 FROM [dbo].[TSEG_ACCION]	WHERE [FUN_ID] = @funpa;

	INSERT INTO [dbo].[TSEG_PERMISOS] ([ROL_ID],[ACC_ID],[PMI_NO_VISUALIZAR_MENU],[VERSION]) 
	SELECT @rolAdministradorId, [ACC_ID],0,1 FROM [dbo].[TSEG_ACCION]	WHERE [FUN_ID] = @func;

	INSERT INTO [dbo].[TSEG_PERMISOS] ([ROL_ID],[ACC_ID],[PMI_NO_VISUALIZAR_MENU],[VERSION]) 
	SELECT @rolAdministradorId, [ACC_ID],0,1 FROM [dbo].[TSEG_ACCION]	WHERE [FUN_ID] = @fune;

	INSERT INTO [dbo].[TSEG_PERMISOS] ([ROL_ID],[ACC_ID],[PMI_NO_VISUALIZAR_MENU],[VERSION]) 
	SELECT @rolAdministradorId, [ACC_ID],0,1 FROM [dbo].[TSEG_ACCION]	WHERE [FUN_ID] = @funop;

	INSERT INTO [dbo].[TSEG_PERMISOS] ([ROL_ID],[ACC_ID],[PMI_NO_VISUALIZAR_MENU],[VERSION]) 
	SELECT @rolAdministradorId, [ACC_ID],0,1 FROM [dbo].[TSEG_ACCION]	WHERE [FUN_ID] = @funr;

END

